Vital.vim work under GitHut Actions
vim-jp/vital.vim pull request #701
Opened 2019-12-14 09:15 UTC by tsuyoshicho

Travis/AppVeyor での動作について、GitHub Actions下で動作させる
コンセプトPRです。

必要になったとき、参考にしたり、部分マージしたりする用として保持するため
にPRを作成しました。

2020-02-10 18:46 UTC, lambdalisue commented
@rhysd さんのやつ使うことでわりとさくっと自分の vital モジュールは移行できました。
https://github.com/lambdalisue/vital-Whisky/pull/33/commits/fa20c3c8d72c67fd462ead46a88bbedfef6938c7

本家でも使える気がするのでコメントしておきます。

2020-02-11 00:29 UTC, tsuyoshicho commented
thinca さんのを待つべきかw? みたいなところはありますね (テストできるバージョンの幅の問題)

2020-03-18 06:23 UTC, tsuyoshicho commented
現在 https://github.com/thinca/action-setup-vim を使うと

1. Linux 8.1系がbuildが必要
2. Windows/macのreleaseはluaでエラー(インストールが必要)

とのこと

2020-03-18 09:44 UTC, tsuyoshicho commented
refine
まだWindowsでテストでこけたりする...

2020-03-18 12:10 UTC, tsuyoshicho commented
Note:

CODECOV_TOKEN として secretにcodecov tokenを保持していることを期待した作りです。

2020-03-21 12:03 UTC, ichizok commented
* `brew install` は lua だけでよいのでは？
* lua bottle のパッケージサイズは120KB程度なのでキャッシュ処理を入れるよりダウンロードした方が早いです。

2020-03-21 12:11 UTC, ichizok commented
参考:
https://github.com/ichizok/vital.vim/runs/523925111
https://github.com/ichizok/vital.vim/runs/523925114
https://github.com/ichizok/vital.vim/runs/523925115
https://github.com/ichizok/vital.vim/runs/523925117

`brew update` 30s ~ 80s
`brew install lua` 10s 以下

2020-03-21 13:54 UTC, tsuyoshicho commented
ありがとうございます。とりこむほうがいいかもしれませんね...

よく考えるとバージョンの問題もあるし。

2020-03-21 20:41 UTC, ichizok commented
あと、homebrew が必要なのは macvim の時だけですね。
(macos-latest 環境の type==vim は lua 無効でビルドされている)

2020-03-21 23:53 UTC, ichizok commented
homebrew消して、macvimの起動時に `luadll` を設定するwrapperを作る案。

```diff
--- a/.github/workflows/buildtest.yml
+++ b/.github/workflows/buildtest.yml
@@ -33,24 +32,9 @@ jobs:
         if: matrix.os == 'ubuntu-latest'
         run: |
           sudo apt-get update
-      - name: Get brew cache directory
-        if: matrix.os == 'macos-latest'
-        # see https://tamakiii.hatenablog.com/entry/2019/11/21/213847
-        id: brew-cache
-        run: |
-          echo "::set-output name=dir::$(brew --cache)/downloads"
-      - name: Set brew cache
-        if: matrix.os == 'macos-latest'
-        uses: actions/cache@v1
-        with:
-          path: ${{ steps.brew-cache.outputs.dir }}
-          key: ${{ runner.os }}-brew
-      - name: Setup brew - libs
+      - name: Setup lua
         if: matrix.os == 'macos-latest'
-        run: |
-          brew config
-          brew update
-          brew install lua luajit
+        uses: xpol/setup-lua@v0.2
       - name: Setup pip
         run: |
           sudo pip3 install -U pip
@@ -74,14 +58,27 @@ jobs:
         with:
           vim_version: '${{ matrix.vim }}'
           vim_type: '${{ matrix.type }}'
+      - name: Setup MacVim
+        if: matrix.os == 'macos-latest' && matrix.type == 'macvim'
+        env:
+          VIM_EXECUTABLE: ${{ steps.vim.outputs.executable }}
+        run: |
+          mkdir -p ${GITHUB_WORKSPACE}/.bin
+          cat <<EOT | tee ${GITHUB_WORKSPACE}/.bin/${VIM_EXECUTABLE}
+          #!/bin/bash
+          exec "$(command -v ${VIM_EXECUTABLE})" --cmd 'set luadll=${GITHUB_WORKSPACE}/.lua/lib/liblua.dylib' "\$@"
+          EOT
+          chmod +x ${GITHUB_WORKSPACE}/.bin/${VIM_EXECUTABLE}
       - name: Run test
         env:
           THEMIS_VIM: ${{ steps.vim.outputs.executable }}
           THEMIS_PROFILE: ${{ github.workspace }}/vim-profile-${{ runner.os }}-${{ matrix.vim }}-${{ matrix.type }}.txt
         run: |
+          export PATH=${GITHUB_WORKSPACE}/.bin:${PATH}
           git clone --depth 1 --branch ${THEMIS_VERSION} --single-branch https://github.com/thinca/vim-themis  ${GITHUB_WORKSPACE}/vim-themis
           git clone --depth 1                                            https://github.com/Shougo/vimproc.vim ${GITHUB_WORKSPACE}/vimproc
           (cd ${GITHUB_WORKSPACE}/vimproc && make)
+          which ${THEMIS_VIM}
           ${THEMIS_VIM} --version
           ${GITHUB_WORKSPACE}/vim-themis/bin/themis --runtimepath ${GITHUB_WORKSPACE}/vimproc --exclude ConcurrentProcess --reporter dot
       - name: Collect coverage
```

2020-03-22 01:30 UTC, tsuyoshicho commented
xpol/setup-lua@v0.2
はちょっと諦めてたので、やってみます。

$THEMIS_ARGS つかって、もうちょっと簡素にできそう...

2020-03-22 10:13 UTC, tsuyoshicho commented
設定を `.themisrc` として流し込むことで対応、Linuxも8.1 buildに対応

2020-08-05 06:11 UTC, lambdalisue commented
What's the state of this PR. I'm really looking forward to this.

2020-09-24 07:32 UTC, tsuyoshicho commented on test/System/Process/Vimproc.vimspec
> +        " End
Windowsのテスト in AppVeyor ですが、そこでしか走らせないものをoutにしてたので、ここではコメントアウトとしています。

ローカルテストも走らなくなりますが...Linux/macで確認できているので当座としてこうしています(よりよい方法があれば対応したい)

2020-09-24 07:33 UTC, tsuyoshicho commented on test/Async/Promise.vimspec
> +      sleep 10m
キーを入れてから状態変化までにwaitがないので追加しています(たまに失敗するため)

2020-09-24 07:36 UTC, tsuyoshicho commented on test/Async/Promise.vimspec
> +      Assert Compare(done, '<=', 1000)
この修正系は同じ処理を複数やらないほうが時間的に正確なためです。

2020-09-24 07:36 UTC, tsuyoshicho commented on test/Async/Promise.vimspec
> +      Assert Equals(P.wait(p, { 'interval': 1050 }), ['resolved', v:null])
実測でも短かい方へブレることもあるため、それを見越した時間に変更

2020-09-24 07:37 UTC, tsuyoshicho commented on test/Async/Promise.vimspec
> +      Assert Equals(P.wait(p, { 'interval': 340 }), ['resolved', v:null])
時間余裕の調整+ブレ吸収として 200 * 5ではなく 340 * 3 = 1020 を待ち時間とし、それをチェックするようにしています。

2020-09-24 07:37 UTC, tsuyoshicho commented on test/Async/Later.vimspec
> +      sleep 20m
こちらも、エンキューしている分を処理するに 10 mだとどうしてもNGになりやすいので調整しています。(Vimの内部の動作やそれにともなうtimerなどのテストの想定が多少変った可能性もありますが)

2020-09-24 08:14 UTC, tsuyoshicho commented
全テストPassはするようになったので WIP ではなく review 待ち、としていますが入れるかは別で。
マージするときは、汚くないようにsquash mergeしたほうがいいかなとは思います。

課題
- テストの調整とかは妥当?

2020-09-24 23:21 UTC, ujihisa approved these changes
Commit messages need change

2020-09-25 03:18 UTC, tsuyoshicho commented
Commit message fix. just a moment.

2020-09-26 13:07 UTC, tsuyoshicho commented
非同期系テストのタイミング調整は現在別に多少見直しなどしていますので、こちらのは暫定的であると考えてください(ご意見があればなんなりと)

2020-09-26 14:26 UTC, lambdalisue requested changes
Using `master` on GHA is not recommended.

2020-09-26 14:26 UTC, lambdalisue commented on .github/workflows/reviewdog.yml
> +        uses: actions/checkout@v1
It would be better to use `@v2`

2020-09-26 14:26 UTC, lambdalisue commented on .github/workflows/reviewdog.yml
> +        uses: actions/checkout@v1
`@v2`

2020-09-26 14:26 UTC, lambdalisue commented on .github/workflows/reviewdog.yml
> +        uses: actions/checkout@v1
`@v2`

2020-09-26 14:26 UTC, lambdalisue commented on .github/workflows/reviewdog.yml
> +        uses: actions/checkout@v1
`@v2`

2020-09-26 14:26 UTC, lambdalisue commented on .github/workflows/reviewdog.yml
> +  vital-throw-message:
What is "vital-throw-message"? I could not imagine the behavior or purpose from the name.

2020-09-26 14:26 UTC, lambdalisue commented on .github/workflows/vimhelptagcheck.yml
> +        uses: actions/checkout@master
It *should* be `@v2`

2020-09-26 14:26 UTC, lambdalisue commented on .github/workflows/vimhelptagcheck.yml
> +        uses: tsuyoshicho/action-vimhelp-tagname-check@master
It's better to use tag or revision instead of `master`

2020-09-26 14:28 UTC, tsuyoshicho commented on .github/workflows/reviewdog.yml
> +        uses: actions/checkout@v1
This code be old, rewrite

2020-09-26 14:45 UTC, tsuyoshicho commented on .github/workflows/reviewdog.yml
> +  vital-throw-message:
This name is no good. I'm using the local lint-throw.go, so I want to give it a nice name.

2020-09-26 14:49 UTC, tsuyoshicho commented on .github/workflows/reviewdog.yml
> +        uses: actions/checkout@v1
Thanks, fixed.

2020-09-26 14:50 UTC, tsuyoshicho commented on .github/workflows/reviewdog.yml
> +        uses: actions/checkout@v1
Thanks, fixed.

2020-09-26 14:50 UTC, tsuyoshicho commented on .github/workflows/reviewdog.yml
> +        uses: actions/checkout@v1
Thanks, fixed.

2020-09-26 14:50 UTC, tsuyoshicho commented on .github/workflows/reviewdog.yml
> +        uses: actions/checkout@v1
Thanks, fixed.

2020-09-26 14:50 UTC, tsuyoshicho commented on .github/workflows/vimhelptagcheck.yml
> +        uses: actions/checkout@master
Thanks, fixed.

2020-09-26 14:50 UTC, tsuyoshicho commented on .github/workflows/vimhelptagcheck.yml
> +        uses: tsuyoshicho/action-vimhelp-tagname-check@master
Thanks, fixed.

2020-09-26 15:20 UTC, lambdalisue commented on .github/workflows/reviewdog.yml
> +  vital-throw-message:
ここが何をやっているのかがわかっていないのでなんとも言い難いです...

2020-09-26 15:21 UTC, lambdalisue approved these changes
LGTM

2020-09-26 23:46 UTC, tsuyoshicho commented on .github/workflows/reviewdog.yml
> +  vital-throw-message:
えー、現在のCIのテストはぜんぶやるを基本として、vital.vimが内製でもってる、例外スロー系テストをやってる、なんですが...、このテストのテスト的確認ができてないので、それはそれで問題なんですよね...、折を見て棚卸し的確認が必要なんだろうと思います。

2020-09-26 23:48 UTC, tsuyoshicho commented
Thanks, workflow refine in vital-codec, but I forgot backport :-<
(Test fail for timing issue... need tune up)

2020-09-27 01:58 UTC, lambdalisue commented on .github/workflows/reviewdog.yml
> +  vital-throw-message:
難易度。棚卸しはこのprとは関係ないので、僕としてはこのままで良いと思います👍

2020-09-27 04:19 UTC, tsuyoshicho commented on .github/workflows/reviewdog.yml
> +  vital-throw-message:
了解です。名前、機能性については、もしはいったなら、その後にということで

2021-02-09 11:35 UTC, tsuyoshicho commented
現在コンフリクト他がありますので、もう一度調整が入ります。

2021-02-11 11:03 UTC, tsuyoshicho commented
調整し、コミットの整理をしました。
(themisの自動追従はちょっとできませんでした...)

2021-02-16 00:16 UTC, ujihisa commented
:thinking: hmm

```
Failures:
  1) vital vital-Vital-object .import supports cyclic dependencies
     function 1772() abort dict  Line:1  [ Absolute Line: 404 ]  (/tmp/v2Z8DzE/37)
     function <SNR>14_eval(expr, scopes) abort  Line:11  [ Absolute Line: 212 ]  (~/work/vital.vim/vital.vim/vim-themis/autoload/themis/helper/command.vim)
     function <SNR>195_import(name, ...) abort dict  Line:11  [ Absolute Line: 49 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/testplugin.vim)
     function <SNR>195__import(name) abort dict  Line:18  [ Absolute Line: 161 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/testplugin.vim)
     
     vital: fail to call ._vital_loaded(): Vim(function):E127: Cannot redefine function <SNR>193__vital_loaded: It is in use from:

  2) vital vital-Vital-object .load supports cyclic dependencies
     function 1790() abort dict  Line:3  [ Absolute Line: 553 ]  (/tmp/v2Z8DzE/37)
     function <SNR>14_eval(expr, scopes) abort  Line:11  [ Absolute Line: 212 ]  (~/work/vital.vim/vital.vim/vim-themis/autoload/themis/helper/command.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return1() abort  Line:1  [ Absolute Line: 23 ]  (~/work/vital.vim/vital.vim/test/_testdata/vital/testplugin/autoload/vital/_testplugin/Cyclic1.vim)
     function <SNR>193_return()  This function is already deleted.
     
     Vim(return):E132: Function call depth is higher than 'maxfuncdepth'
```
https://github.com/vim-jp/vital.vim/pull/701/checks?ch [...]

2021-02-16 00:41 UTC, tsuyoshicho commented
> 🤔 hmm

Previews run was success(Windows vimproc only NG)... why??

2021-02-16 01:26 UTC, ujihisa approved these changes

2021-02-16 01:27 UTC, ujihisa commented
hmm :thinking: 

> Travis CI - Pull Request Expected — Waiting for status to be reported
> (Required)

2021-02-16 10:14 UTC, tsuyoshicho commented
> hmm 🤔
> 
> > Travis CI - Pull Request Expected — Waiting for status to be reported
> > (Required)

If do merging so, Required setting unlock & change needing in this PR.

2021-02-21 10:45 UTC, tsuyoshicho commented on test/System/Process/Vimproc.vimspec
> +        " End
GHAだと `CI` の定義があるそうなので、それも判定対象に含めることで対応

2021-07-08 08:28 UTC, tsuyoshicho commented
https://github.com/vim-jp/vital.vim/pull/769
が反映されないと、latestでテストが失敗する

2021-07-25 22:47 UTC, tsuyoshicho commented
codecov v2対応OK
(とくに対応が必要な記述をしていなかった、他も含め動作確認済み)

2021-07-26 00:19 UTC, thinca approved these changes

2021-07-26 00:19 UTC, merged

2021-07-28 15:03 UTC, lambdalisue commented
🎉